[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ConcreteDropout"
version = "0.3.0"
authors = [
  { name="Aurelio Amerio", email="aurelio.amerio@ific.uv.es" },
]
description = "Concrete Dropout implementation for Tensorflow 2 and PyTorch"
dependencies = []
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/aurelio-amerio/ConcreteDropout"
"Bug Tracker" = "https://github.com/aurelio-amerio/ConcreteDropout/issues"

[project.optional-dependencies]
tensorflow = ["tensorflow>=2.0"]
jax = ["jax[cuda]", "jaxlib", "flax", "optax"] # or just "jax" if no cuda
pytorch = ["torch"]